[profile.default]
src = "src"
out = "out"
libs = ['lib']
gas_reports = [
    'NameRegistry',
    'ScoreBoard',
    'MockDoublyLinkedListAddress',
    'MockDoublyLinkedListBytes',
    'MockDoublyLinkedListUint256'
]
allow_internal_expect_revert = true

[fuzz]
runs = 10_000