[profile.default]
src = "src"
out = "out"
libs = ['lib']
gas_reports = [
    'NameRegistry',
    'ScoreBoard',
    'DoublyLinkedListAddress',
    'DoublyLinkedListBytes',
    'DoublyLinkedListUint256'
]
allow_internal_expect_revert = true